all:
	docker build --tag="gitlab.testbed.se:5000/ostdb_client" .
	
# push:
# 	docker push "gitlab.testbed.se:5000/ostdb_bertrand"
# 
# stop:
# 	docker stop tmpost
# rm:
# 	docker rm tmpost
# start:
# 	docker run -d -p 8070:8070 -p 4242:4242 -p 60030:60030	 --link ddbroker:broker --name=tmpost  gitlab.testbed.se:5000/ostdb_bertrand
# inter:
# 	docker run -it -p 8070:8070 -p 4242:4242 -p 60030:60030	--link ddbroker:broker --name=tmpost  gitlab.testbed.se:5000/ostdb_bertrand
# bash:
# 	docker run -it -p 8070:8070 -p 4242:4242 -p 60030:60030	--link ddbroker:broker --name=tmpost  gitlab.testbed.se:5000/ostdb_bertrand /bin/bash
