# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'getoptlong'

opts = GetoptLong.new(
  [ '--docker-registry-username', GetoptLong::REQUIRED_ARGUMENT ],
  [ '--docker-registry-password', GetoptLong::REQUIRED_ARGUMENT ],
  [ '--github-branch', GetoptLong::OPTIONAL_ARGUMENT ],
  [ '--vm-memory', GetoptLong::OPTIONAL_ARGUMENT ],
  [ '--vm-cores', GetoptLong::OPTIONAL_ARGUMENT ]
)

username=''
password=''
memory=3072
cores=2
branch='new_elastic_router'

username='unify'
password='unify-demo-stress-out'

opts.each do |opt, arg|
  case opt
    when '--docker-registry-username'
      username=arg
	when '--docker-registry-password'
	  password=arg	
	when '--github-branch'
	  branch=arg	
	when '--vm-memory'
	  memory=arg	
	when '--vm-cores'
	  cores=arg	
  end
end

# opened tcp ports
# 10001 : ctrl-app gui
# 10002 : ovs ssh
# 3000  : grafana
# 9090  : virtualizer
# 9999  : un-gui
# 8081  : cadvisor
# 4242  : openTSDB
# 5555  : DD broker
# 8082  : 2nd cadvisor
# 9096  : Prometheus
  
Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.provider "virtualbox" do |v|
      v.memory = "#{memory}"
      v.cpus = "#{cores}"
  config.vm.network "forwarded_port", guest: 10001, host: 10001
  config.vm.network "forwarded_port", guest: 10002, host: 10002
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.network "forwarded_port", guest: 9090, host: 9090
  config.vm.network "forwarded_port", guest: 9999, host: 9999
  config.vm.network "forwarded_port", guest: 8081, host: 8081
  config.vm.network "forwarded_port", guest: 4242, host: 4242
  config.vm.network "forwarded_port", guest: 5555, host: 5555
  config.vm.network "forwarded_port", guest: 8082, host: 8082
  config.vm.network "forwarded_port", guest: 9096, host: 9096


end

  config.vm.network "private_network", ip: "10.1.1.2"
  config.vm.network "private_network", ip: "10.1.2.2"
  config.vm.network "private_network", ip: "10.1.3.2"
  config.vm.network "private_network", ip: "10.1.4.2"

  # normally the ansible provider should be used, however, because
  # Ansible is not well supported on Windows machines, ansible is triggered from 
  # the vm itself via a shell script
   
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y ansible
    python /vagrant/provisioning/deploy.py -u "#{username}" -p "#{password}" -b "#{branch}" -c all
    sudo ansible-playbook -i "localhost," -c local /vagrant/provisioning/install-playbook.yml
  SHELL
   
end
